<?php

namespace AppBundle\Repository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *  createQueryBuilder() : constructeur de requête
     *      definir l'alias de l'entité
     *  méthodes reprennant les noms des commandes SQL :
     *      select() :
     *          choix des propriétés de l'entité en utilisant l'alias
     *          renvoie un array de array
     *  getQuery() : execution de la requête / appel de cette méthode en avant dernière position
     *  récupération des résultats : dernière position
     *      getResult() : renvoie un array d'objets
     */
    public function testQuery()
    {
        $query = $this->createQueryBuilder('courses')
            ->select('courses.name, courses.slug')
            ->where('courses.name = :nameParams')
            ->andWhere('courses.name LIKE :likeParams')
            ->setParameters([
                'nameParams' => 'Web Designer',
                'likeParams' => '%design%'
            ])
            ->getQuery()
            ->getSingleResult();
            //->getResult();

        // requête de regroupement
        /*$query = $this->createQueryBuilder('courses')
            ->getQuery()
            ->getResult();*/

        return $query;
    }
}
