<?php

namespace AppBundle\Repository;

/**
 * OperatingSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatingSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
